/**
 * Generates live, interactive location UI: a type-ahead autocomplete field
 * and a cascading country/state/city picker, backed by the real
 * `csc.search.autocomplete()` endpoint at runtime — unlike react-dropdown.ts,
 * nothing is pre-fetched or baked in at generation time.
 */

export type GeneratorTarget = 'nextjs' | 'react-browser';

/**
 * Shown before any react-browser file is written, and repeated verbatim in
 * the generated README so the warning survives past the initial CLI run.
 */
export const BROWSER_KEY_WARNING =
  'Your API key will be visible in browser JavaScript and network requests — ' +
  'there is no server to keep it secret. Before using this component, create a ' +
  'key in your CSC dashboard restricted to your approved website origin(s). ' +
  'Never use an unrestricted/server key here.';

const AUTOCOMPLETE_ROUTE_PATH = 'app/api/csc-search/route.ts';
const TRACKED_PRICING_URL =
  'https://countrystatecity.in/pricing?source=cli&campaign=location_components&package=cli';
const TRACKED_SIGNUP_URL =
  'https://app.countrystatecity.in?source=cli&campaign=location_components&package=cli';

/**
 * Next.js Route Handler that holds the real API key server-side and proxies
 * to `csc.search.autocomplete()`. Shared by both the autocomplete and
 * location-picker Next.js generators since it's the same one endpoint
 * called with different `type`/`country`/`state` filters.
 */
export function generateAutocompleteRoute(): string {
  return `// ${AUTOCOMPLETE_ROUTE_PATH}
// Generated by @countrystatecity/cli
//
// Keeps CSC_API_KEY server-side. The browser never sees it — it only ever
// talks to this same-origin route.

import { NextRequest, NextResponse } from 'next/server';
import {
  createCSCClient,
  ValidationError,
  AuthenticationError,
  FeatureRestrictedError,
  RateLimitError,
} from '@countrystatecity/sdk';
import type { SearchResultType } from '@countrystatecity/sdk';

export async function GET(request: NextRequest) {
  const apiKey = process.env.CSC_API_KEY;
  if (!apiKey) {
    return NextResponse.json(
      { error: 'CSC_API_KEY is not configured on the server. See .env.example.' },
      { status: 500 }
    );
  }

  const searchParams = request.nextUrl.searchParams;
  const query = searchParams.get('query') ?? '';
  const type = (searchParams.get('type') ?? 'city') as SearchResultType;
  const country = searchParams.get('country') ?? undefined;
  const state = searchParams.get('state') ?? undefined;

  const csc = createCSCClient({ apiKey });

  try {
    const { data } = await csc.search.autocomplete({ query, type, country, state, limit: 10 });
    return NextResponse.json(data);
  } catch (error) {
    if (error instanceof ValidationError) {
      return NextResponse.json({ error: error.message }, { status: 400 });
    }
    if (error instanceof AuthenticationError) {
      return NextResponse.json({ error: 'Invalid API key.' }, { status: 401 });
    }
    if (error instanceof FeatureRestrictedError) {
      return NextResponse.json(
        { error: error.message, requiredPlan: error.requiredPlan, upgradeUrl: error.upgradeUrl },
        { status: 403 }
      );
    }
    if (error instanceof RateLimitError) {
      return NextResponse.json({ error: error.message }, { status: 429 });
    }
    return NextResponse.json({ error: 'Search failed. Please try again.' }, { status: 502 });
  }
}
`;
}

export function generateEnvExample(target: GeneratorTarget): string {
  if (target === 'nextjs') {
    return `# Generated by @countrystatecity/cli
# Copy to .env.local and fill in your real key — never commit .env.local.
# Get a key at ${TRACKED_SIGNUP_URL}
CSC_API_KEY=YOUR_API_KEY_HERE
`;
  }

  return `# Generated by @countrystatecity/cli
# Copy to .env.local (Vite) and fill in your real key — never commit .env.local.
# This key ships to the browser: restrict it to your site's origin(s) in the
# CSC dashboard before using it. See the generated README for details.
VITE_CSC_API_KEY=YOUR_API_KEY_HERE
`;
}

// ---------------------------------------------------------------------------
// Shared JSX fragments (textual sharing across the four component variants —
// each generated file below stays fully self-contained; only the *generator*
// code here is factored).
// ---------------------------------------------------------------------------

const HOOK_IMPORTS = `import { useCallback, useEffect, useId, useRef, useState } from 'react';`;

function statusBlock(indent: string): string {
  return `${indent}{status === 'loading' && (
${indent}  <div role="status" className="csc-field-status">Searching…</div>
${indent})}
${indent}{status === 'plan-restricted' && (
${indent}  <div role="alert" className="csc-field-status csc-field-error">
${indent}    {planMessage ?? 'This search requires a higher plan. Upgrade to enable it.'}
${indent}    {' '}<a href={UPGRADE_URL} target="_blank" rel="noreferrer">View API plans</a>
${indent}  </div>
${indent})}
${indent}{status === 'rate-limited' && (
${indent}  <div role="alert" className="csc-field-status csc-field-error">
${indent}    Too many requests — please slow down and try again shortly.
${indent}  </div>
${indent})}
${indent}{status === 'network-error' && (
${indent}  <div role="alert" className="csc-field-status csc-field-error">
${indent}    Couldn't reach the search service. Check your connection and try again.
${indent}  </div>
${indent})}
${indent}{status === 'empty' && (
${indent}  <div role="status" className="csc-field-status">No results found.</div>
${indent})}`;
}

function listboxBlock(indent: string): string {
  return `${indent}{isOpen && results.length > 0 && (
${indent}  <ul id={listboxId} role="listbox" className="csc-field-list">
${indent}    {results.map((result, index) => (
${indent}      <li
${indent}        key={\`\${result.type}-\${'iso2' in result ? result.iso2 : result.id}-\${index}\`}
${indent}        id={\`\${listboxId}-option-\${index}\`}
${indent}        role="option"
${indent}        aria-selected={index === activeIndex}
${indent}        className={index === activeIndex ? 'active' : ''}
${indent}        onMouseDown={(e) => { e.preventDefault(); selectResult(result); }}
${indent}      >
${indent}        {result.label}
${indent}      </li>
${indent}    ))}
${indent}  </ul>
${indent})}`;
}

const KEYBOARD_HANDLER = `  function handleKeyDown(e: React.KeyboardEvent<HTMLInputElement>) {
    if (!isOpen || results.length === 0) return;

    if (e.key === 'ArrowDown') {
      e.preventDefault();
      setActiveIndex((i) => (i + 1) % results.length);
    } else if (e.key === 'ArrowUp') {
      e.preventDefault();
      setActiveIndex((i) => (i <= 0 ? results.length - 1 : i - 1));
    } else if (e.key === 'Enter') {
      if (activeIndex >= 0) {
        e.preventDefault();
        selectResult(results[activeIndex]);
      }
    } else if (e.key === 'Escape') {
      setIsOpen(false);
      setActiveIndex(-1);
    } else if (e.key === 'Tab') {
      setIsOpen(false);
    }
  }`;

// ---------------------------------------------------------------------------
// autocomplete — Next.js (same-origin fetch to the generated Route Handler)
// ---------------------------------------------------------------------------

export function generateAutocompleteComponentNextjs(): string {
  return `// components/LocationAutocomplete.tsx
// Generated by @countrystatecity/cli
// Calls the same-origin /api/csc-search route — see ${AUTOCOMPLETE_ROUTE_PATH}.
// The API key never reaches this file or the browser.
'use client';

${HOOK_IMPORTS}
import type { IAutocompleteResult, SearchResultType } from '@countrystatecity/sdk';

export interface LocationAutocompleteProps {
  /** Entity type to search. Defaults to 'city'. */
  type?: SearchResultType;
  /** Restrict results to this country (ISO2), when type is 'state' or 'city'. */
  country?: string;
  /** Restrict results to this state (ISO2). Requires \`country\`. */
  state?: string;
  placeholder?: string;
  /** Called with the full, typed result on selection — use its id/iso2/
   * country_code/state_code as the stable identifier, never \`label\`. */
  onSelect?: (result: IAutocompleteResult) => void;
  className?: string;
}

type Status = 'idle' | 'loading' | 'success' | 'empty' | 'plan-restricted' | 'rate-limited' | 'network-error';

const MIN_QUERY_LENGTH = 2;
const DEBOUNCE_MS = 250;
const UPGRADE_URL = '${TRACKED_PRICING_URL}';

export default function LocationAutocomplete({
  type = 'city',
  country,
  state,
  placeholder = 'Search for a place…',
  onSelect,
  className = '',
}: LocationAutocompleteProps) {
  const [query, setQuery] = useState('');
  const [results, setResults] = useState<IAutocompleteResult[]>([]);
  const [status, setStatus] = useState<Status>('idle');
  const [planMessage, setPlanMessage] = useState<string | null>(null);
  const [isOpen, setIsOpen] = useState(false);
  const [activeIndex, setActiveIndex] = useState(-1);

  const debounceRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const abortRef = useRef<AbortController | null>(null);
  const listboxId = useId();

  const runSearch = useCallback((q: string) => {
    abortRef.current?.abort();

    if (q.trim().length < MIN_QUERY_LENGTH) {
      setResults([]);
      setStatus('idle');
      setIsOpen(false);
      return;
    }

    const controller = new AbortController();
    abortRef.current = controller;
    setStatus('loading');
    setResults([]);
    setIsOpen(false);
    setActiveIndex(-1);

    const params = new URLSearchParams({ query: q, type });
    if (country) params.set('country', country);
    if (state) params.set('state', state);

    fetch(\`/api/csc-search?\${params.toString()}\`, { signal: controller.signal })
      .then(async (res) => {
        if (controller.signal.aborted) return;
        if (res.status === 403) {
          const body = await res.json().catch(() => null);
          setPlanMessage(body?.error ?? null);
          setStatus('plan-restricted');
          setResults([]);
          return;
        }
        if (res.status === 429) {
          setStatus('rate-limited');
          setResults([]);
          return;
        }
        if (!res.ok) {
          setStatus('network-error');
          setResults([]);
          return;
        }
        const data: IAutocompleteResult[] = await res.json();
        if (controller.signal.aborted) return;
        setResults(data);
        setStatus(data.length === 0 ? 'empty' : 'success');
        setActiveIndex(-1);
        setIsOpen(true);
      })
      .catch((err) => {
        if (err instanceof DOMException && err.name === 'AbortError') return;
        setStatus('network-error');
        setResults([]);
      });
  }, [type, country, state]);

  useEffect(() => {
    return () => {
      abortRef.current?.abort();
      if (debounceRef.current) clearTimeout(debounceRef.current);
    };
  }, []);

  useEffect(() => {
    abortRef.current?.abort();
    if (debounceRef.current) clearTimeout(debounceRef.current);
    debounceRef.current = null;
    setQuery('');
    setResults([]);
    setStatus('idle');
    setIsOpen(false);
    setActiveIndex(-1);
  }, [type, country, state]);

  function handleChange(e: React.ChangeEvent<HTMLInputElement>) {
    const value = e.target.value;
    setQuery(value);

    if (debounceRef.current) clearTimeout(debounceRef.current);
    debounceRef.current = setTimeout(() => runSearch(value), DEBOUNCE_MS);
  }

  function selectResult(result: IAutocompleteResult) {
    if (debounceRef.current) clearTimeout(debounceRef.current);
    debounceRef.current = null;
    abortRef.current?.abort();
    abortRef.current = null;
    setQuery(result.label);
    setIsOpen(false);
    setResults([]);
    setStatus('idle');
    onSelect?.(result);
  }

${KEYBOARD_HANDLER}

  const activeDescendant = activeIndex >= 0 ? \`\${listboxId}-option-\${activeIndex}\` : undefined;

  return (
    <div className={\`csc-field \${className}\`} style={{ position: 'relative' }}>
      <input
        type="text"
        role="combobox"
        aria-expanded={isOpen}
        aria-controls={listboxId}
        aria-autocomplete="list"
        aria-activedescendant={activeDescendant}
        aria-label={placeholder}
        value={query}
        placeholder={placeholder}
        onChange={handleChange}
        onKeyDown={handleKeyDown}
        onFocus={() => { if (results.length > 0) setIsOpen(true); }}
        onBlur={() => setTimeout(() => setIsOpen(false), 150)}
        autoComplete="off"
      />

${statusBlock('      ')}

${listboxBlock('      ')}
    </div>
  );
}
`;
}

// ---------------------------------------------------------------------------
// autocomplete — react-browser (calls the SDK directly, client-side)
// ---------------------------------------------------------------------------

export function generateAutocompleteComponentBrowser(): string {
  return `// components/LocationAutocomplete.tsx
// Generated by @countrystatecity/cli
//
// WARNING: ${BROWSER_KEY_WARNING}

${HOOK_IMPORTS}
import { useMemo } from 'react';
import {
  createCSCClient,
  ValidationError,
  FeatureRestrictedError,
  RateLimitError,
} from '@countrystatecity/sdk';
import type { IAutocompleteResult, SearchResultType } from '@countrystatecity/sdk';

export interface LocationAutocompleteProps {
  /** An origin-restricted CSC API key. Never hardcode this — read it from an
   * env var (e.g. import.meta.env.VITE_CSC_API_KEY) and pass it in. */
  apiKey: string;
  /** Entity type to search. Defaults to 'city'. */
  type?: SearchResultType;
  /** Restrict results to this country (ISO2), when type is 'state' or 'city'. */
  country?: string;
  /** Restrict results to this state (ISO2). Requires \`country\`. */
  state?: string;
  placeholder?: string;
  /** Called with the full, typed result on selection — use its id/iso2/
   * country_code/state_code as the stable identifier, never \`label\`. */
  onSelect?: (result: IAutocompleteResult) => void;
  className?: string;
}

type Status = 'idle' | 'loading' | 'success' | 'empty' | 'plan-restricted' | 'rate-limited' | 'network-error';

const MIN_QUERY_LENGTH = 2;
const DEBOUNCE_MS = 250;
const UPGRADE_URL = '${TRACKED_PRICING_URL}';

export default function LocationAutocomplete({
  apiKey,
  type = 'city',
  country,
  state,
  placeholder = 'Search for a place…',
  onSelect,
  className = '',
}: LocationAutocompleteProps) {
  const csc = useMemo(() => createCSCClient({ apiKey }), [apiKey]);

  const [query, setQuery] = useState('');
  const [results, setResults] = useState<IAutocompleteResult[]>([]);
  const [status, setStatus] = useState<Status>('idle');
  const [planMessage, setPlanMessage] = useState<string | null>(null);
  const [isOpen, setIsOpen] = useState(false);
  const [activeIndex, setActiveIndex] = useState(-1);

  const debounceRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const abortRef = useRef<AbortController | null>(null);
  const listboxId = useId();

  const runSearch = useCallback((q: string) => {
    abortRef.current?.abort();

    if (q.trim().length < MIN_QUERY_LENGTH) {
      setResults([]);
      setStatus('idle');
      setIsOpen(false);
      return;
    }

    const controller = new AbortController();
    abortRef.current = controller;
    setStatus('loading');
    setResults([]);
    setIsOpen(false);
    setActiveIndex(-1);

    csc.search
      .autocomplete({ query: q, type, country, state, limit: 10 }, { signal: controller.signal })
      .then(({ data }) => {
        if (controller.signal.aborted) return;
        setResults(data);
        setStatus(data.length === 0 ? 'empty' : 'success');
        setActiveIndex(-1);
        setIsOpen(true);
      })
      .catch((err) => {
        if (err instanceof DOMException && err.name === 'AbortError') return;
        if (err instanceof FeatureRestrictedError) {
          setPlanMessage(err.message);
          setStatus('plan-restricted');
          setResults([]);
          return;
        }
        if (err instanceof RateLimitError) {
          setStatus('rate-limited');
          setResults([]);
          return;
        }
        if (err instanceof ValidationError) {
          setStatus('network-error');
          setResults([]);
          return;
        }
        setStatus('network-error');
        setResults([]);
      });
  }, [csc, type, country, state]);

  useEffect(() => {
    return () => {
      abortRef.current?.abort();
      if (debounceRef.current) clearTimeout(debounceRef.current);
    };
  }, []);

  useEffect(() => {
    abortRef.current?.abort();
    if (debounceRef.current) clearTimeout(debounceRef.current);
    debounceRef.current = null;
    setQuery('');
    setResults([]);
    setStatus('idle');
    setIsOpen(false);
    setActiveIndex(-1);
  }, [type, country, state]);

  function handleChange(e: React.ChangeEvent<HTMLInputElement>) {
    const value = e.target.value;
    setQuery(value);

    if (debounceRef.current) clearTimeout(debounceRef.current);
    debounceRef.current = setTimeout(() => runSearch(value), DEBOUNCE_MS);
  }

  function selectResult(result: IAutocompleteResult) {
    if (debounceRef.current) clearTimeout(debounceRef.current);
    debounceRef.current = null;
    abortRef.current?.abort();
    abortRef.current = null;
    setQuery(result.label);
    setIsOpen(false);
    setResults([]);
    setStatus('idle');
    onSelect?.(result);
  }

${KEYBOARD_HANDLER}

  const activeDescendant = activeIndex >= 0 ? \`\${listboxId}-option-\${activeIndex}\` : undefined;

  return (
    <div className={\`csc-field \${className}\`} style={{ position: 'relative' }}>
      <input
        type="text"
        role="combobox"
        aria-expanded={isOpen}
        aria-controls={listboxId}
        aria-autocomplete="list"
        aria-activedescendant={activeDescendant}
        aria-label={placeholder}
        value={query}
        placeholder={placeholder}
        onChange={handleChange}
        onKeyDown={handleKeyDown}
        onFocus={() => { if (results.length > 0) setIsOpen(true); }}
        onBlur={() => setTimeout(() => setIsOpen(false), 150)}
        autoComplete="off"
      />

${statusBlock('      ')}

${listboxBlock('      ')}
    </div>
  );
}
`;
}

// ---------------------------------------------------------------------------
// location-picker — cascading country → state → city
// ---------------------------------------------------------------------------

/**
 * Builds the shared body of LocationPicker.tsx: an internal ComboboxField
 * plus the three cascading instances. `fetcherBody` is the data-fetching
 * snippet (either same-origin fetch or a direct SDK call) inlined into
 * ComboboxField's runSearch — the one place the two targets differ.
 */
function locationPickerBody(fetcherBody: string, extraImports: string, extraProps: string, cscInit: string): string {
  return `${HOOK_IMPORTS}
${extraImports}
import type { IAutocompleteResult, SearchResultType } from '@countrystatecity/sdk';

export interface LocationPickerValue {
  country: IAutocompleteResult | null;
  state: IAutocompleteResult | null;
  city: IAutocompleteResult | null;
}

export interface LocationPickerProps {
${extraProps}  /** Called whenever the selection changes at any level. */
  onChange?: (value: LocationPickerValue) => void;
  className?: string;
}

type Status = 'idle' | 'loading' | 'success' | 'empty' | 'plan-restricted' | 'rate-limited' | 'network-error';

const MIN_QUERY_LENGTH = 2;
const DEBOUNCE_MS = 250;
const UPGRADE_URL = '${TRACKED_PRICING_URL}';

interface ComboboxFieldProps {
${extraProps}  type: SearchResultType;
  country?: string;
  state?: string;
  placeholder: string;
  disabled?: boolean;
  onSelect: (result: IAutocompleteResult) => void;
}

function ComboboxField({${extraProps ? ' apiKey,' : ''} type, country, state, placeholder, disabled, onSelect }: ComboboxFieldProps) {
${cscInit}
  const [query, setQuery] = useState('');
  const [results, setResults] = useState<IAutocompleteResult[]>([]);
  const [status, setStatus] = useState<Status>('idle');
  const [planMessage, setPlanMessage] = useState<string | null>(null);
  const [isOpen, setIsOpen] = useState(false);
  const [activeIndex, setActiveIndex] = useState(-1);

  const debounceRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const abortRef = useRef<AbortController | null>(null);
  const listboxId = useId();

  const runSearch = useCallback((q: string) => {
    abortRef.current?.abort();

    if (q.trim().length < MIN_QUERY_LENGTH) {
      setResults([]);
      setStatus('idle');
      setIsOpen(false);
      return;
    }

    const controller = new AbortController();
    abortRef.current = controller;
    setStatus('loading');
    setResults([]);
    setIsOpen(false);
    setActiveIndex(-1);

${fetcherBody}
  }, [type, country, state${extraProps ? ', csc' : ''}]);

  useEffect(() => {
    return () => {
      abortRef.current?.abort();
      if (debounceRef.current) clearTimeout(debounceRef.current);
    };
  }, []);

  useEffect(() => {
    abortRef.current?.abort();
    if (debounceRef.current) clearTimeout(debounceRef.current);
    debounceRef.current = null;
    setQuery('');
    setResults([]);
    setStatus('idle');
    setIsOpen(false);
    setActiveIndex(-1);
  }, [type, country, state]);

  function handleChange(e: React.ChangeEvent<HTMLInputElement>) {
    const value = e.target.value;
    setQuery(value);

    if (debounceRef.current) clearTimeout(debounceRef.current);
    debounceRef.current = setTimeout(() => runSearch(value), DEBOUNCE_MS);
  }

  function selectResult(result: IAutocompleteResult) {
    if (debounceRef.current) clearTimeout(debounceRef.current);
    debounceRef.current = null;
    abortRef.current?.abort();
    abortRef.current = null;
    setQuery(result.label);
    setIsOpen(false);
    setResults([]);
    setStatus('idle');
    onSelect(result);
  }

${KEYBOARD_HANDLER}

  const activeDescendant = activeIndex >= 0 ? \`\${listboxId}-option-\${activeIndex}\` : undefined;

  return (
    <div className="csc-field" style={{ position: 'relative' }}>
      <input
        type="text"
        role="combobox"
        aria-expanded={isOpen}
        aria-controls={listboxId}
        aria-autocomplete="list"
        aria-activedescendant={activeDescendant}
        aria-label={placeholder}
        aria-disabled={disabled}
        value={query}
        placeholder={placeholder}
        disabled={disabled}
        onChange={handleChange}
        onKeyDown={handleKeyDown}
        onFocus={() => { if (results.length > 0) setIsOpen(true); }}
        onBlur={() => setTimeout(() => setIsOpen(false), 150)}
        autoComplete="off"
      />

${statusBlock('      ')}

${listboxBlock('      ')}
    </div>
  );
}

export default function LocationPicker({${extraProps ? ' apiKey,' : ''} onChange, className = '' }: LocationPickerProps) {
  const [selectedCountry, setSelectedCountry] = useState<IAutocompleteResult | null>(null);
  const [selectedState, setSelectedState] = useState<IAutocompleteResult | null>(null);
  const [selectedCity, setSelectedCity] = useState<IAutocompleteResult | null>(null);

  const countryCode = selectedCountry && 'iso2' in selectedCountry ? selectedCountry.iso2 : undefined;
  const stateCode = selectedState && 'iso2' in selectedState ? selectedState.iso2 : undefined;

  function handleCountrySelect(result: IAutocompleteResult) {
    setSelectedCountry(result);
    setSelectedState(null);
    setSelectedCity(null);
    onChange?.({ country: result, state: null, city: null });
  }

  function handleStateSelect(result: IAutocompleteResult) {
    setSelectedState(result);
    setSelectedCity(null);
    onChange?.({ country: selectedCountry, state: result, city: null });
  }

  function handleCitySelect(result: IAutocompleteResult) {
    setSelectedCity(result);
    onChange?.({ country: selectedCountry, state: selectedState, city: result });
  }

  return (
    <div className={\`csc-location-picker \${className}\`}>
      <ComboboxField${extraProps ? ' apiKey={apiKey}' : ''}
        type="country"
        placeholder="Search for a country…"
        onSelect={handleCountrySelect}
      />
      <ComboboxField${extraProps ? ' apiKey={apiKey}' : ''}
        key={\`state-\${countryCode ?? 'none'}\`}
        type="state"
        country={countryCode}
        placeholder="Search for a state…"
        disabled={!countryCode}
        onSelect={handleStateSelect}
      />
      <ComboboxField${extraProps ? ' apiKey={apiKey}' : ''}
        key={\`city-\${countryCode ?? 'none'}-\${stateCode ?? 'none'}\`}
        type="city"
        country={countryCode}
        state={stateCode}
        placeholder="Search for a city…"
        disabled={!stateCode}
        onSelect={handleCitySelect}
      />
    </div>
  );
}
`;
}

export function generateLocationPickerComponentNextjs(): string {
  const fetcherBody = `    const params = new URLSearchParams({ query: q, type });
    if (country) params.set('country', country);
    if (state) params.set('state', state);

    fetch(\`/api/csc-search?\${params.toString()}\`, { signal: controller.signal })
      .then(async (res) => {
        if (controller.signal.aborted) return;
        if (res.status === 403) {
          const body = await res.json().catch(() => null);
          setPlanMessage(body?.error ?? null);
          setStatus('plan-restricted');
          setResults([]);
          return;
        }
        if (res.status === 429) {
          setStatus('rate-limited');
          setResults([]);
          return;
        }
        if (!res.ok) {
          setStatus('network-error');
          setResults([]);
          return;
        }
        const data: IAutocompleteResult[] = await res.json();
        if (controller.signal.aborted) return;
        setResults(data);
        setStatus(data.length === 0 ? 'empty' : 'success');
        setActiveIndex(-1);
        setIsOpen(true);
      })
      .catch((err) => {
        if (err instanceof DOMException && err.name === 'AbortError') return;
        setStatus('network-error');
        setResults([]);
      });`;

  const header = `// components/LocationPicker.tsx
// Generated by @countrystatecity/cli
// Calls the same-origin /api/csc-search route — see ${AUTOCOMPLETE_ROUTE_PATH}.
// The API key never reaches this file or the browser.
'use client';

`;

  return header + locationPickerBody(fetcherBody, '', '', '');
}

export function generateLocationPickerComponentBrowser(): string {
  const fetcherBody = `    csc.search
      .autocomplete({ query: q, type, country, state, limit: 10 }, { signal: controller.signal })
      .then(({ data }) => {
        if (controller.signal.aborted) return;
        setResults(data);
        setStatus(data.length === 0 ? 'empty' : 'success');
        setActiveIndex(-1);
        setIsOpen(true);
      })
      .catch((err) => {
        if (err instanceof DOMException && err.name === 'AbortError') return;
        if (err instanceof FeatureRestrictedError) {
          setPlanMessage(err.message);
          setStatus('plan-restricted');
          setResults([]);
          return;
        }
        if (err instanceof RateLimitError) {
          setStatus('rate-limited');
          setResults([]);
          return;
        }
        setStatus('network-error');
        setResults([]);
      });`;

  const header = `// components/LocationPicker.tsx
// Generated by @countrystatecity/cli
//
// WARNING: ${BROWSER_KEY_WARNING}

`;

  const extraImports = `import { useMemo } from 'react';
import { createCSCClient, FeatureRestrictedError, RateLimitError } from '@countrystatecity/sdk';`;
  const extraProps = `  /** An origin-restricted CSC API key. Never hardcode this — read it from an
   * env var (e.g. import.meta.env.VITE_CSC_API_KEY) and pass it in. */
  apiKey: string;
`;
  const cscInit = `  const csc = useMemo(() => createCSCClient({ apiKey }), [apiKey]);
`;

  return header + locationPickerBody(fetcherBody, extraImports, extraProps, cscInit);
}

// ---------------------------------------------------------------------------
// READMEs
// ---------------------------------------------------------------------------

export function generateAutocompleteReadme(target: GeneratorTarget): string {
  if (target === 'nextjs') {
    return `# LocationAutocomplete (Next.js)

Generated by \`@countrystatecity/cli\`.

Runtime autocomplete requires a Professional or Business API plan. [Compare plans](${TRACKED_PRICING_URL}).

## Files

- \`${AUTOCOMPLETE_ROUTE_PATH}\` — server Route Handler; holds your API key.
- \`components/LocationAutocomplete.tsx\` — client component.
- \`.env.example\` — copy to \`.env.local\` and set \`CSC_API_KEY\`.

## Setup

1. \`npm install @countrystatecity/sdk\`
2. Copy \`.env.example\` to \`.env.local\` and set \`CSC_API_KEY\` to a real key
   from ${TRACKED_SIGNUP_URL} — this key stays server-side.
3. Use the component:

\`\`\`tsx
import LocationAutocomplete from '@/components/LocationAutocomplete';

<LocationAutocomplete
  type="city"
  country="IN"
  onSelect={(result) => console.log(result.id, result.label)}
/>
\`\`\`

## Behavior

- Waits ~250ms after typing before searching; ignores queries under 2 characters.
- Cancels an in-flight search when a newer one starts.
- Shows distinct states for loading, no results, a plan-restricted (403)
  error, a rate-limit (429) error, and network errors.
- Full keyboard support (arrow keys, Enter, Escape, Tab) and ARIA combobox
  roles for screen readers.
- \`onSelect\` receives the full typed result — use its \`id\`/\`iso2\`/
  \`country_code\`/\`state_code\`, not \`label\`, as the stable identifier.

## Styling

Minimal by design — override via the \`.csc-field\`, \`.csc-field-list\`,
\`.csc-field-status\`, and \`.csc-field-error\` class names, or pass \`className\`.
`;
  }

  return `# LocationAutocomplete (React, browser)

Generated by \`@countrystatecity/cli\`.

Runtime autocomplete requires a Professional or Business API plan. [Compare plans](${TRACKED_PRICING_URL}).

> **WARNING:** ${BROWSER_KEY_WARNING}

## Files

- \`components/LocationAutocomplete.tsx\` — calls the CSC API directly from the browser.
- \`.env.example\` — copy to \`.env.local\` and set \`VITE_CSC_API_KEY\`.

## Setup

1. \`npm install @countrystatecity/sdk\`
2. In the [CSC dashboard](${TRACKED_SIGNUP_URL}), create a key restricted to your site's origin(s).
3. Copy \`.env.example\` to \`.env.local\` and set \`VITE_CSC_API_KEY\`.
4. Use the component:

\`\`\`tsx
import LocationAutocomplete from './components/LocationAutocomplete';

<LocationAutocomplete
  apiKey={import.meta.env.VITE_CSC_API_KEY}
  type="city"
  country="IN"
  onSelect={(result) => console.log(result.id, result.label)}
/>
\`\`\`

## Behavior

Same as the Next.js version — 250ms debounce, 2-character minimum, request
cancellation, distinct loading/empty/plan-restricted/rate-limit/network-error
states, full keyboard support, and ARIA combobox roles.

## Styling

Minimal by design — override via the \`.csc-field\`, \`.csc-field-list\`,
\`.csc-field-status\`, and \`.csc-field-error\` class names, or pass \`className\`.
`;
}

export function generateLocationPickerReadme(target: GeneratorTarget): string {
  if (target === 'nextjs') {
    return `# LocationPicker (Next.js)

Generated by \`@countrystatecity/cli\`. Cascading country → state → city picker.

Runtime autocomplete requires a Professional or Business API plan. [Compare plans](${TRACKED_PRICING_URL}).

## Files

- \`${AUTOCOMPLETE_ROUTE_PATH}\` — server Route Handler; holds your API key.
- \`components/LocationPicker.tsx\` — client component.
- \`.env.example\` — copy to \`.env.local\` and set \`CSC_API_KEY\`.

## Setup

1. \`npm install @countrystatecity/sdk\`
2. Copy \`.env.example\` to \`.env.local\` and set \`CSC_API_KEY\`.
3. Use the component:

\`\`\`tsx
import LocationPicker from '@/components/LocationPicker';

<LocationPicker onChange={(value) => console.log(value.country, value.state, value.city)} />
\`\`\`

## Behavior

- Each level is its own live search field (250ms debounce, 2-character
  minimum, request cancellation, per-field loading/empty/error states).
- The state field is disabled until a country is chosen; the city field is
  disabled until a state is chosen.
- Changing the country clears both the state and city selections. Changing
  the state clears only the city selection.
- \`onChange\` receives the full typed result for each level — use
  \`id\`/\`iso2\`/\`country_code\`/\`state_code\`, not \`label\`, as the stable
  identifier.

## Styling

Minimal by design — override via the \`.csc-location-picker\`, \`.csc-field\`,
\`.csc-field-list\`, \`.csc-field-status\`, and \`.csc-field-error\` class names.
`;
  }

  return `# LocationPicker (React, browser)

Generated by \`@countrystatecity/cli\`. Cascading country → state → city picker.

Runtime autocomplete requires a Professional or Business API plan. [Compare plans](${TRACKED_PRICING_URL}).

> **WARNING:** ${BROWSER_KEY_WARNING}

## Files

- \`components/LocationPicker.tsx\` — calls the CSC API directly from the browser.
- \`.env.example\` — copy to \`.env.local\` and set \`VITE_CSC_API_KEY\`.

## Setup

1. \`npm install @countrystatecity/sdk\`
2. In the [CSC dashboard](${TRACKED_SIGNUP_URL}), create a key restricted to your site's origin(s).
3. Copy \`.env.example\` to \`.env.local\` and set \`VITE_CSC_API_KEY\`.
4. Use the component:

\`\`\`tsx
import LocationPicker from './components/LocationPicker';

<LocationPicker
  apiKey={import.meta.env.VITE_CSC_API_KEY}
  onChange={(value) => console.log(value.country, value.state, value.city)}
/>
\`\`\`

## Behavior

Same cascading behavior as the Next.js version — see above.

## Styling

Minimal by design — override via the \`.csc-location-picker\`, \`.csc-field\`,
\`.csc-field-list\`, \`.csc-field-status\`, and \`.csc-field-error\` class names.
`;
}
